#!/bin/sh

# run from directory where this script is
# needs 3 arguments:
# $./matdyn-calc ecutwfcmin ecutwfcstep ecutwfcmax

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
MASTER_DIR=`pwd`
K_DIM=4
for i in `seq $1 $2 $3` ; do
	echo "On lattice param = 10.333"
	mkdir -p si.$i
	cd si.$i
	echo "Calculating for ecutwfc = $i"
	ECUTWFC=$i
	ECUTRHO=`expr 8 \* $ECUTWFC`
	#The self-consistent calculation script
	cat > si.scf.$i.in << EOF		
&control
	calculation = 'scf',
	prefix = 'silicon.$i',
	tstress = .true.,
/
&system
	ibrav = 2,
	celldm(1) = 10.333,
	nat = 2,
	ntyp = 1,
	ecutwfc = $ECUTWFC,
	ecutrho = $ECUTRHO,
/
&electrons
	mixing_beta = 0.7,
	conv_thr = 1.0d-8,
/
ATOMIC_SPECIES
 Si 28.086 si_pbe_v1.uspp.F.UPF.txt
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS automatic
 $K_DIM $K_DIM $K_DIM	1 1 1
EOF
	mpirun -np 4 pw.x < si.scf.$i.in > si.scf.$i.out
	echo "Finished this one"
	cd $MASTER_DIR
done
